Repository OZ-Coding-School/oz_externship_fe_02_team2, pull requests merged in 2025-09, with the labels that each got.

#2 Feature/1 setup mocks
  .hintrc
  Postman_Usage_Guide.md
  db.json
  openapi.yaml
  package-lock.json
  package.json
  postman_collection.json
  public/mockServiceWorker.js
  src/api/admin.ts
  src/api/client.ts
  src/hooks/useAdminList.ts
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/mocks.md
  src/mocks/msw.handlers.ts
  tsconfig.json
  vite.config.ts
Labels: documentation, enhancement

#7 chore: 이슈&PR 템플릿 작성
  .github/ISSUE_TEMPLATE/공용-이슈-템플릿.md
  .github/PULL_REQUEST_TEMPLATE/공용-PR-템플릿.md
Labels: documentation

#9 [chore] README 브랜치명 수정, 폴더 별 역할 추가
  README.md
Labels: documentation

#19 [feat] 디자인 시스템 반영한 컬러/타이포그래피 테마 및 변수 설정
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/auto-assign.yml
  src/index.css
Labels: enhancement

#25 Feature/21 common input
  src/components/ui/icons.tsx
  src/components/ui/input/Input.styles.ts
  src/components/ui/input/Input.tsx
  src/test-pages/InputTest.tsx
  src/types/input.ts
  src/types/table.ts
Labels: enhancement

#29 Feature/16 pagination
  src/components/ui/Pagination/EllipsisPopover.tsx
  src/components/ui/Pagination/Pagination.styles.ts
  src/components/ui/Pagination/Pagination.tsx
  src/components/ui/Pagination/Pagination.types.ts
  src/components/ui/Pagination/Pagination.utils.ts
  src/test-pages/PaginationTest.tsx
Labels: enhancement

#42 [fix] 토스트 알림 발생 시 좌우 여백 클릭 안 됨 현상 해결
  src/components/ui/Toast/Toast.styles.ts
  src/components/ui/Toast/ToastContainer.tsx
Labels: bug

#54 [feat] 버튼 커스텀용 props 추가
  src/assets/icons/close_g.svg
  src/components/ui/Button/Button.tsx
  src/test-pages/ButtonTest.tsx
  src/types/button.ts
Labels: enhancement

#60 [feat] 사이드바 레이아웃 기본 틀(접힘-펼침) 구현 (데스크톱)
  src/assets/icons/hamburger.svg
  src/assets/icons/nav_member.svg
  src/assets/icons/nav_member_dashboard_active.svg
  src/assets/icons/nav_member_dashboard_default.svg
  src/assets/icons/nav_member_users_active.svg
  src/assets/icons/nav_member_users_default.svg
  src/assets/icons/nav_member_withdraw_active.svg
  src/assets/icons/nav_member_withdraw_default.svg
  src/assets/icons/nav_recruit.svg
  src/assets/icons/nav_recruit_join_active.svg
  src/assets/icons/nav_recruit_join_default.svg
  src/assets/icons/nav_recruit_posts_active.svg
  src/assets/icons/nav_recruit_posts_default.svg
  src/assets/icons/nav_study.svg
  src/assets/icons/nav_study_groups_active.svg
  src/assets/icons/nav_study_groups_default.svg
  src/assets/icons/nav_study_lectures_active.svg
  src/assets/icons/nav_study_lectures_default.svg
  src/assets/icons/nav_study_reviews_active.svg
  src/assets/icons/nav_study_reviews_default.svg
  src/components/Sidebar/Sidebar.tsx
  src/index.css
  src/test-pages/SidebarTest.tsx
Labels: enhancement

#73 Feature/72 table badge connect
  src/components/table/Badges.tsx
  src/components/table/Table.types.ts
  src/components/table/feature/CoursesTable.tsx
  src/components/table/feature/StudyGrouptsTable.tsx
  src/components/table/feature/UsersTable.tsx
  src/components/table/feature/withdrawalsTable.tsx
  src/components/ui/Badge/Badge.tsx
  src/lib/index.ts
  src/lib/mappers.ts
  src/test-pages/UsersTableTest.tsx
Labels: enhancement

#94 [Feat] StudyGroup 관련 모달 컴포넌트 구현 및 리팩토링
  src/components/ui/Modal/feature/Study/CourseCard.tsx
  src/components/ui/Modal/feature/Study/MemberList.tsx
  src/components/ui/Modal/feature/Study/Study.types.ts
  src/components/ui/Modal/feature/Study/StudyGroupDetailLeft.tsx
  src/components/ui/Modal/feature/Study/StudyGroupDetailModal.tsx
  src/components/ui/Modal/feature/Study/StudyGroupDetailRight.tsx
  src/components/ui/Modal/feature/Withdrawal/WithdrawalUserView.tsx
  src/components/ui/Modal/parts/Title.tsx
  src/lib/mappers.ts
  src/test-pages/StudyModalTest.tsx
Labels: documentation, enhancement

#98 Feature/96 table sort
  src/assets/icons/sort-ascend.svg
  src/assets/icons/sort-default.svg
  src/assets/icons/sort-descend.svg
  src/components/table/DataTable.tsx
  src/components/table/SortIcon.tsx
  src/components/table/feature/CoursesTable.tsx
  src/components/table/feature/StudyGrouptsTable.tsx
  src/components/table/feature/UsersTable.tsx
  src/components/table/feature/withdrawalsTable.tsx
  src/components/table/sort.ts
  src/types/table.ts
Labels: documentation, enhancement

#105 [Feat] MSW 와 백엔드 API 토글 할 수 있는 기본 API 모듈 생성
  index.html
  package-lock.json
  src/api/admin.ts
  src/api/client.ts
  src/api/http.ts
  src/api/modules/users.ts
  src/api/toggles/mockToggle.ts
  src/components/table/Table.types.ts
  src/hooks/index.ts
  src/hooks/useAdminList.ts
  src/lib/mappers.ts
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/db.ts
  src/mocks/handlers/admin/users.ts
  src/mocks/handlers/index.ts
  src/mocks/seeds/users.seed.ts
  src/mocks/server.ts
  src/mocks/utils.ts
  src/pages/main/MainPage.tsx
  src/test-pages/UserAdminTest.tsx
  vite.config.ts
Labels: enhancement

#106 [Feat] 회원관리 페이지 API 연결
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/api/modules/users.ts
  src/components/table/DataTable.tsx
  src/components/table/Table.types.ts
  src/components/table/feature/UsersTable.tsx
  src/components/ui/Modal/Modal.tsx
  src/components/ui/Modal/feature/User/UserDelete.tsx
  src/components/ui/Modal/feature/User/UserDetail.tsx
  src/components/ui/Modal/feature/User/useUserFormHandlers.ts
  src/hooks/useFormHandlers.ts
  src/hooks/useModal.ts
  src/lib/mappers.ts
  src/main.tsx
  src/mocks/db.ts
  src/mocks/handlers/admin/users.ts
  src/mocks/startMsw.ts
  src/pages/admin/UserManage.tsx
  src/pages/main/PlaceHolderPage.tsx
  src/routes/TestRoutes.tsx
  src/types/table.ts
  src/types/users.ts
Labels: enhancement

#108 [Feat] 회원관리 테이블에 검색 /정렬 필터 동기화
  src/api/modules/users.ts
  src/components/table/DataTable.tsx
  src/components/table/Table.types.ts
  src/components/table/TableWithFilters.tsx
  src/components/table/feature/TableFilterBar.tsx
  src/components/table/feature/Users/UsersFilterBar.tsx
  src/components/table/feature/Users/UsersTable.tsx
  src/components/table/queryString.ts
  src/components/ui/Modal/feature/User/User.types.ts
  src/constants/table/table.ts
  src/hooks/useTableFilters.ts
  src/hooks/useTableQuery.ts
  src/lib/mappers.ts
  src/lib/tableFiltering.ts
  src/main.tsx
  src/pages/admin/UserManage.tsx
  src/pages/main/MainPage.tsx
  src/test-pages/UserAdminTest.tsx
  src/test-pages/UsersTableTest.tsx
  src/types/table.ts
Labels: enhancement

#118 [Refactor] MSW 시드 변경 및 각 페이지 수정사항 반영
  src/components/ui/Modal/feature/User/User.types.ts
  src/mocks/handlers/admin/users.ts
  src/mocks/handlers/admin/withdrawals.ts
  src/mocks/seeds/users.seed.ts
  src/mocks/seeds/withdrawals.seed.ts
  src/pages/admin/UserManage.tsx
  src/pages/admin/UserWithdrawal.tsx
Labels: bug

#120 [Test] CORS TEST
  src/api/modules/users.ts
  src/pages/admin/UserManage.tsx
  src/pages/study/StudyManage.tsx
  vercel.json
  vite.config.ts
Labels: bug

#123 [Feat] 대시보드(차트) 페이지 UI & 라우팅
  package-lock.json
  package.json
  src/components/charts/DoughnutChart/DoughnutChart.plugin.ts
  src/components/charts/DoughnutChart/DoughnutChart.tsx
  src/components/charts/VerticalBarChart/Join/JoinBar.tsx
  src/components/charts/VerticalBarChart/Join/config/annual.ts
  src/components/charts/VerticalBarChart/Join/config/index.ts
  src/components/charts/VerticalBarChart/Join/config/monthly.ts
  src/components/charts/VerticalBarChart/Leave/LeaveBar.tsx
  src/components/charts/VerticalBarChart/Leave/config/annual.ts
  src/components/charts/VerticalBarChart/Leave/config/index.ts
  src/components/charts/VerticalBarChart/Leave/config/monthly.ts
  src/components/charts/VerticalBarChart/Reason/ReasonBar.tsx
  src/components/charts/VerticalBarChart/Reason/config/competitorService.ts
  src/components/charts/VerticalBarChart/Reason/config/dissatisfaction.ts
  src/components/charts/VerticalBarChart/Reason/config/index.ts
  src/components/charts/VerticalBarChart/Reason/config/lowUsage.ts
  src/components/charts/VerticalBarChart/Reason/config/other.ts
  src/components/charts/VerticalBarChart/Reason/config/privacyConcerns.ts
  src/components/charts/VerticalBarChart/VerticalBarChart.options.ts
  src/components/charts/VerticalBarChart/VerticalBarChart.plugin.ts
  src/components/charts/VerticalBarChart/VerticalBarChart.tsx
  src/lib/getPageString.ts
  src/mocks/handlers/admin/users.ts
  src/pages/dashboard/DashboardPage.tsx
  src/pages/dashboard/sub-pages/Join.tsx
  src/pages/dashboard/sub-pages/Leave.tsx
  src/pages/dashboard/sub-pages/Reason.tsx
  src/pages/dashboard/sub-pages/common/Section.tsx
  src/pages/dashboard/sub-pages/common/constants.ts
  src/pages/dashboard/sub-pages/common/index.ts
  src/pages/main/MainPage.tsx
  src/routes/TestRoutes.tsx
Labels: enhancement

#128 [Feat] 지원 내역 관리 MSW 구현
  src/mocks/handlers/admin/studyAssistance.ts
  src/mocks/seeds/studyAssistance.seed.ts
Labels: enhancement

#135 [Feat] 유저 관리 API 연결
  src/api/modules/users.ts
  src/components/ui/Modal/feature/User/UserDelete.tsx
  src/components/ui/Modal/feature/User/UserDetail.tsx
  src/components/ui/Modal/feature/User/UserRoleChange.tsx
  src/components/ui/Modal/feature/User/useUserFormHandlers.ts
  src/pages/admin/UserManage.tsx
Labels: enhancement

#145 [Feat] 스터디 구인 공고 관리 모달 추가
  src/api/http.ts
  src/api/modules/recruitments.ts
  src/components/table/feature/Recruitments/RecruitmentsFilterBar.tsx
  src/components/table/feature/Recruitments/RecruitmentsTable.tsx
  src/components/table/feature/TableFilterBar.tsx
  src/components/ui/Modal/feature/Recruiment/RecruitmentDetailLeft.tsx
  src/components/ui/Modal/feature/Recruiment/RecruitmentDetailModal.tsx
  src/components/ui/Modal/feature/Recruiment/RecruitmentDetailRight.tsx
  src/components/ui/Modal/feature/Recruiment/TagFilterModal.tsx
  src/mocks/browser.ts
  src/mocks/handlers/admin/recruitments.ts
  src/mocks/handlers/index.ts
  src/mocks/seeds/recruitment.seed.ts
  src/pages/admin/RecruitmnetsManage.tsx
  src/types/AdminRecruitments.types.ts
Labels: enhancement
